#!/bin/bash
#
# Edit by vastxiao
# Date at 20170506 

export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_root'

cd $(dirname $0)
MAINPATH=$(pwd)
cd hexo_root || exit 1
hexo version || exit 1
hexo clean
hexo gen
hexo deploy || exit 1
cd ${MAINPATH}
git add . -A
git commit -a -m "update bloginit at $(date +'%F %T')"
git push

